# Generated by Django 6.0.7 on 2026-07-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
