# Generated by Django 6.0.7 on 2026-07-10 12:06

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_domain_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='sites/favicons/', validators=[apps.core.validators.validate_file_size])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sites/logos/', validators=[apps.core.validators.validate_file_size])),
                ('global_css', models.FileField(blank=True, null=True, upload_to='sites/css/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css']), apps.core.validators.validate_file_size])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['-created_at'],
            },
        ),
    ]
