# Generated by Django 6.0.7 on 2026-07-10 06:17

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('html_file', models.FileField(upload_to='headers/html/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), core.validators.validate_file_size])),
                ('css_file', models.FileField(blank=True, null=True, upload_to='headers/css/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css']), core.validators.validate_file_size])),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
