# Generated by Django 6.0.7 on 2026-07-10 12:06

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('page_type', models.CharField(choices=[('standard', 'Standard'), ('landing', 'Landing Page'), ('blog', 'Blog')], default='standard', max_length=20)),
                ('enable', models.BooleanField(default=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('html', models.FileField(blank=True, null=True, upload_to='pages/html/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html']), apps.core.validators.validate_file_size])),
                ('css', models.FileField(blank=True, null=True, upload_to='pages/css/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css']), apps.core.validators.validate_file_size])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_slug_per_site')],
            },
        ),
    ]
