# Generated by Django 6.0.7 on 2026-07-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero Banner'), ('text', 'Text Block'), ('gallery', 'Image Gallery'), ('pricing_table', 'Pricing Table'), ('contact_form', 'Contact Form')], max_length=30)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
